getherprj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import getherapp.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', getherapp.views.index, name='index'),
    path('base/', getherapp.views.base, name='base'), #나중에 base는 지울것
    path('feedback/', getherapp.views.feedback, name='feedback'),
    path('feedback_cp/', getherapp.views.feedback_cp, name='feedback_cp'),
    path('introduce/', getherapp.views.introduce, name='introduce'),
    path('dormitory/', getherapp.views.dormitory, name='dormitory'),
    path('gdin_gwan', getherapp.views.gdin_gwan, name='gdin_gwan'),
    path('im_gwan/', getherapp.views.im_gwan, name='im_gwan'),
    path('jg_gwan/', getherapp.views.jg_gwan, name='jg_gwan'),
    path('library/', getherapp.views.library, name='library'),
    path('mgell_gwan/', getherapp.views.mgell_gwan, name='mgell_gwan'),
    path('nn_gwan/', getherapp.views.nn_gwan, name='nn_gwan'),
    path('pb_hall/', getherapp.views.pb_hall, name='pb_hall'),
    path('sbdr_school/', getherapp.views.sbdr_school, name='sbdr_school'),
    path('scn_gwan/', getherapp.views.scn_gwan, name='scn_gwan'),
    path('sy_gwan/', getherapp.views.sy_gwan, name='sy_gwan'),
    path('wd_gwan/', getherapp.views.wd_gwan, name='wd_gwan'),
    path('classroom/<str:unit_id>/<str:id>/', getherapp.views.classroom, name='classroom'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

getherapp/models.py
from email.policy import default
from django.db import models 
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

class Subject(models.Model):
    kind = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Professor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Classroom(models.Model):
    kwan_num = models.SmallIntegerField(
        validators=[
            MinValueValidator(1), MaxValueValidator(13)
            ]
    ) 
    kwan_name = models.CharField(max_length=50)
    unit = models.CharField(max_length=50, null=True)
    image = models.ImageField(upload_to='images/classroom', null=True, blank=True)

    def __str__(self):
        return str(self.unit)

class Class(models.Model):
    div = models.SmallIntegerField(null=True,
        validators=[
            MinValueValidator(1), MaxValueValidator(3)]
    )    
    date1 = models.CharField(max_length=10)
    date2 = models.CharField(max_length=10, null=True)
    time1 = models.TimeField()
    time2 = models.TimeField()
    prof_id = models.ForeignKey(Professor, null=True, on_delete=models.SET_NULL, related_name='class_profid')
    room_id = models.ForeignKey(Classroom, null=True, on_delete=models.SET_NULL, related_name='class_roomid')
    sub_id = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='class_subid')

    def __str__(self):
        return self.room_id

class Feedback(models.Model):
    user_id = models.CharField(max_length=50)
    feedback_date = models.DateTimeField(auto_now_add=True)
    user_phonenum = models.CharField(max_length=100, null=True) #추가해봤어염
    feedback_content = models.TextField(default = "글을 작성해주세요.")
 
    def __str__(self):
        return self.user_id

        # models 수정

getherapp/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['user_id', 'user_phonenum', 'feedback_content']

        widgets = {
            'user_id': forms.TextInput(attrs={'placeholder': 'Name'}),
            'user_phonenum': forms.TextInput(attrs={'placeholder': 'PhoneNumber'}),
            'feedback_content': forms.Textarea(attrs={'placeholder': 'Feedback Here'}),
        } 

getherapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from datetime import datetime, time
from getherapp.models import Classroom, Class
from .forms import FeedbackForm
from django.db.models import Q

# Create your views here.
# 이게 현재 시간과 요일 가져오는 것
# 트랜스외국인이 돼야 한다면 순서 바꿔주면 됨
days = [ '금', '토', '일', '월', '화', '수', '목',]
now = datetime.now()
now_date = now.date()
now_time = now.time()
weekday = now.weekday()
now_weekday = days[weekday]

am9 = time(9, 00, 00, 000000)
am9_30 = time(9, 30, 00, 000000)
am10 = time(10, 00, 00, 000000)
am10_30 = time(10, 30, 00, 000000)
am11 = time(11, 00, 00, 000000)
am11_30 = time(11, 30, 00, 000000)
pm12 = time(12, 00, 00, 000000)
pm12_30 = time(12, 30, 00, 000000)
pm1 = time(13, 00, 00, 000000)
pm1_30 = time(13, 30, 00, 000000)
pm2 = time(14, 00, 00, 000000)
pm2_30 = time(14, 30, 00, 000000)
pm3 = time(15, 00, 00, 000000)
pm3_30 = time(15, 30, 00, 000000)
pm4 = time(16, 00, 00, 000000)
pm4_30 = time(16, 30, 00, 000000)
pm5 = time(17, 00, 00, 000000)
pm5_30 = time(17, 30, 00, 000000)
pm6 = time(18, 00, 00, 000000)
pm6_30 = time(18, 30, 00, 000000)
pm7 = time(19, 00, 00, 000000)

time_list = [am9, am9_30, am10, am10_30, am11, am11_30, pm12, pm12_30, pm1, pm1_30, pm2, pm2_30, pm3, pm3_30, pm4, pm4_30, pm5, pm5_30, pm6, pm6_30,pm7]

def base(request):
    return render(request, 'base.html')

def index(request):
    return render(request, 'index.html')

def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.feedback_date = timezone.now()
            form.save()
            return redirect('feedback_cp')
    else:
        form = FeedbackForm()
        return render(request, 'feedback.html', {'form': form})

def feedback_cp(request):
    return render(request, 'feedback_cp.html')

def introduce(request):
    return render(request, 'introduce.html')

# 1관 승연관
def sy_gwan(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "승연관")
    classes = Class.objects.all()
    return render(request, 'class/sy_gwan.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 2관 일만관
def im_gwan(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "일만관")
    classes = Class.objects.all()
    return render(request, 'class/im_gwan.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 3관 월당관
def wd_gwan(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id',).filter(kwan_name = "월당관")
    classes = Class.objects.all()
    return render(request, 'class/wd_gwan.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 5관 나눔관
def nn_gwan(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "나눔관")
    classes = Class.objects.all()
    return render(request, 'class/nn_gwan.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 6관 정보과학관
def jg_gwan(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "정보과학관")
    classes = Class.objects.all()
    return render(request, 'class/jg_gwan.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 7관 새천년관
def scn_gwan(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "새천년관")
    classes = Class.objects.all()
    return render(request, 'class/scn_gwan.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 8관 중앙도서관
def library(request):
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "중앙도서관")
    classes = Class.objects.all()
    return render(request, 'class/library.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 9관 피츠버그홀
def pb_hall(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "피츠버그홀")
    classes = Class.objects.all()
    return render(request, 'class/pb_hall.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 10관 구두인관
def gdin_gwan(request):
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "구두인관")
    classes = Class.objects.all()
    return render(request, 'class/gdin_gwan.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 12관 성베드로학교
def sbdr_school(request):
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "성베드로학교")
    classes = Class.objects.all()
    return render(request, 'class/sbdr_school.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 11관 미가엘관
def mgell_gwan(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "미가엘관")
    classes = Class.objects.all()
    return render(request, 'class/mgell_gwan.html',
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 'classrooms':classrooms, 'classes': classes})

# 13관 행복기숙사
def dormitory(request):
    # 이게 모델 내용 가져오는 것
    classrooms = Classroom.objects.order_by('id').filter(kwan_name = "행복기숙사")
    return render(request, 'class/dormitory.html',
    {'classrooms':classrooms})

def classroom(request, unit_id, id): #unit==unit_id==Class.room_id, id==classroom.id
    classroom = get_object_or_404(Classroom, unit = unit_id, id = id)
    classes = Class.objects.all().order_by('time2')

    '''월요일'''
    mon_classes = classes.filter(room_id=id)
    mon_classes = list(mon_classes.filter(Q(date1='월') | Q(date2='월'))) #유닛이 같고 월요일인 강의인 객체들을 쿼리셋에서 리스트로 변환
    mon_test =[] # 월요일 수업이 있으면 요소 추가할 리스트
    for i in mon_classes: 
        mon_test.append(i) 
    if len(mon_test)<1: #월 수업을 추가했는데 리스트 길이가 1도 안된다면 공강임
        mon_classes = '공강'
    else: # 리스트 길이가 1이상이면 공강 아니니까
        mon_classes = classes.filter(room_id=id)
        mon_classes = mon_classes.filter(Q(date1='월') | Q(date2='월')) # 찐 mon_classes에 유닛같은 월수업 객체 모두 담기

    '''화요일'''
    tue_classes = classes.filter(room_id=id)
    tue_classes = list(tue_classes.filter(Q(date1='화') | Q(date2='화')))
    tue_test =[] 
    for i in tue_classes: 
        tue_test.append(i) 
    if len(tue_test)<1: 
        tue_classes = '공강'
    else: 
        tue_classes = classes.filter(room_id=id)
        tue_classes = tue_classes.filter(Q(date1='화') | Q(date2='화'))

    '''수요일'''
    wed_classes = classes.filter(room_id=id)
    wed_classes = list(wed_classes.filter(Q(date1='수') | Q(date2='수')))
    wed_test =[] 
    for i in wed_classes: 
        wed_test.append(i) 
    if len(wed_test)<1: 
        wed_classes = '공강'
    else: 
        wed_classes = classes.filter(room_id=id)
        wed_classes = wed_classes.filter(Q(date1='수') | Q(date2='수'))
        

    '''목요일''' 
    thu_classes = classes.filter(room_id=id)
    thu_classes = list(thu_classes.filter(Q(date1='목') | Q(date2='목')))
    thu_test =[] 
    for i in thu_classes: 
        thu_test.append(i) 
    if len(thu_test)<1: 
        thu_classes = '공강'
    else: 
        thu_classes = classes.filter(room_id=id)
        thu_classes = thu_classes.filter(Q(date1='목') | Q(date2='목'))
        

    '''금요일'''
    fri_classes = classes.filter(room_id=id)
    fri_classes = list(fri_classes.filter(Q(date1='금') | Q(date2='금')))
    fri_test =[]
    for i in fri_classes: 
        fri_test.append(i) 
    if len(fri_test)<1: 
        fri_classes = '공강'
    else: 
        fri_classes = classes.filter(room_id=id)
        fri_classes = fri_classes.filter(Q(date1='금') | Q(date2='금'))


    return render(request, 'classroom.html', 
    {'now_date':now_date, 'now_time':now_time, 'now_weekday':now_weekday, 
    'time_list': time_list, 
    'classroom': classroom, 'classes': classes,
    'mon_classes':mon_classes,'tue_classes':tue_classes,'wed_classes':wed_classes,'thu_classes':thu_classes,'fri_classes':fri_classes,
    'mon_test':mon_test,'tue_test':tue_test,'wed_test':wed_test,
    })

getherapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/build.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/maplogo.png' %}">
    <title>{% block title %} base {% endblock %}</title>
</head>
<body>
    <!-- 전체 사이트 레이아웃을 위한 container -->
    <div class="container">

        <div class="nav">
            <!-- 메뉴바, index 로고  -->
            <div class="nav1">
              <label for="checkbox" class="hbmenu">
                <input type="checkbox" id="checkbox" onclick="menutoggle()">
                <span class="line line-main"></span>
                <span class="line line-split"></span>
              </label>

              <div id="menu__container" class="nmenu">
                <div id="menu__box" class="">
                  <div class="menu_header">
                    <a href="{% url 'index' %}">
                      <img class="nav-img menu_img" src="{% static 'img/logo_ver1.png' %}">
                    </a>
                  </div>
                  <div class="menu_body">
                    <ul class="menu_list">
                      <li><a href="{% url 'introduce' %}"><span><i class="fa-solid fa-map"></i></span><span>소개</span></a></li>
                      <li><a href="{% url 'sy_gwan' %}"><span>1</span><span>승연관</span></a></li>
                      <li><a href="{% url 'im_gwan' %}"><span>2</span><span>일만관</span></a></li>
                      <li><a href="{% url 'wd_gwan' %}"><span>3</span><span>월당관</span></a></li>
                      <li><a href="{% url 'nn_gwan' %}"><span>5</span><span>나눔관</span></a></li>
                      <li><a href="{% url 'jg_gwan' %}"><span>6</span><span>정보과학관</span></a></li>
                      <li><a href="{% url 'scn_gwan' %}"><span>7</span><span>새천년관</span></a></li>
                      <li><a href="{% url 'library' %}"><span>8</span><span>중앙도서관</span></a></li>
                      <li><a href="{% url 'pb_hall' %}"><span>9</span><span>피츠버그홀</span></a></li>
                      <li><a href="{% url 'gdin_gwan' %}"><span>10</span><span>구두인관</span></a></li>
                      <li><a href="{% url 'mgell_gwan' %}"><span>11</span><span>미가엘관</span></a></li>
                      <li><a href="{% url 'sbdr_school' %}"><span>12</span><span>성베드로학교</span></a></li>
                      <li><a href="{% url 'dormitory' %}"><span>13</span><span>행복기숙사</span></a></li>
                    </ul>
                  </div>
                  <div class="menu_footer">
                    <a href="{% url 'feedback' %}">개발자에게 피드백하기</a>
                  </div>
                </div>
              </div>

            </div>
            <div class="nav2">
                <a href="{% url 'index' %}">
                    <img class="nav-img" src="{% static 'img/logo_ver2.png' %}">
                </a>
            </div>
        </div>


        <!-- 안에 컨텐츠 상속 -->
        {% block content %}
        
        {% endblock %}
    </div>
    <script src="{% static 'js/menutoggle.js' %}" type="text/javascript"></script>
</body>
</html>

getherapp/templates/feedback.html
<!-- 피드백 페이지 -->
{% extends 'base.html' %}
{% load static %}
{% block title %} FeedBack {% endblock %}

{% block content %}

<form method = "POST">
    {% csrf_token %}
    <div class="feedback-container">
      <div claass="fb-wrap">
        <div class="fd-head">
          <h1 style="font-size: 3rem"> 🌍 피드백 🌍 </h1>
          <h2 style="font-size: 1.2rem"> 작은 피드백은 개발에 큰 도움이 됩니다. 감사합니다!</h2>
          <span style="color: gray;">피드백을 남겨주신 분들께 추첨을 통해 커피 기프티콘이 제공됩니다:)</span>
        </div>
        <div class="fdform-wrap">
          <div class="inputform">
            <input type="text" name="user_id" maxlength="50" required id="id_user_id">
            <label for="id_user_id ">이름</label>
          </div>
          <div class="inputform">
            <input type="text" name="user_phonenum" maxlength="100" required id="id_user_phonenum" style="margin-bottom: 0;">
            <label for="id_user_id ">전화번호</label>
            <span style="margin-bottom: 30px; color: gray;">(ex. 01012341234)</span>
          </div>
          <div class="inputform">
            <textarea name="feedback_content" cols="40" rows="10" required id="id_feedback_content"></textarea>
            <label for="id_user_id ">피드백 할 내용</label>
          </div>
            <div class="smbutton">
              <a href="{% url 'index' %}">취소</a>
              <button type="submit">제출</button>
            </div>
        </div>

      </div>

    </div>

</form>


{% endblock %}

getherapp/templates/feedback_cp.html
<!-- 피드백 페이지 -->
{% extends 'base.html' %}
{% load static %}
{% block title %} FeedBack {% endblock %}

{% block content %}

<div class="feedback-container">
  <div class="fb-wrap" style="margin-top: 15rem;">
    <div class="fd-head">
        <h1> 🌍 소중한 의견 감사합니다! 🌍 </h1>
        <span style="color: gray;">피드백을 남겨주신 분들께 추첨을 통해 커피 기프티콘이 제공됩니다:)</span>
      </div>
    
      <div class="smbutton">
        <a href="{% url 'index' %}">홈으로</a>
      </div>
  </div>
</div>



{% endblock %}

getherapp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/build.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <title>index</title>
</head>

<body>
    <div class="container">
        <div class="main-nav1">
            <ul class="nav-links">
                <li><a href="{% url 'jg_gwan' %}">정보과학관</a></li>
                <li><a href="{% url 'scn_gwan' %}">새천년관</a></li>
                <li><a href="{% url 'feedback' %}">피드백</a></li>
            </ul>
            
            <div class="toggle1">
                <div class="line-1"></div>
                <div class="line-2"></div>
                <div class="line-3"></div>
            </div>
            <div>
                <a href="{% url 'index' %}">
                    <img class="nav-img" src="{% static 'img/logo_ver1.png' %}" alt="로고ver1">
                </a>
            </div>
        </div> 

        <div class="leo_school">
            <!--맨 위에 있는 요소가 가장 아래에 위치하게 됨-->
            <img id="leo_road" src="static/img/road.png" alt="길"
                onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
            <img id="leo_grounds" src="static/img/sports_grounds.png" alt="운동장"
                onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
            <div class="leo_class">
                <img id="leo_1" src="static/img/1_sy.png" alt="승연관"
                    onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
                <img id="leo_2" src="static/img/2_im.png" alt="일만관"
                    onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
                <img id="leo_3" src="static/img/3_wd.png" alt="월당관"
                    onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
                <img id="leo_5" src="static/img/5_nn.png" alt="나눔관"
                    onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
                <img id="leo_6" src="static/img/6_jg.png" alt="정보과학관"
                    onclick="leo_jg_show(), leo_scn_hide(), out(leo_6), over(leo_1), over(leo_2), over(leo_3), over(leo_5), over(leo_7), over(leo_10), over(leo_11), over(leo_12), over(leo_13)">
                <img id="leo_7" src="static/img/7_scn.png" alt="새천년관"
                    onclick="leo_scn_show(), leo_jg_hide(), out(leo_7), out(leo_scn), over(leo_1), over(leo_2), over(leo_3), over(leo_5), over(leo_6), over(leo_10), over(leo_11), over(leo_12), over(leo_13)">
                <img id="leo_10" src="static/img/10_gdin.png" alt="구두인관"
                    onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
                <img id="leo_11" src="static/img/11_sbdr.png" alt="성베드로학교"
                    onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
                <img id="leo_12" src="static/img/12_mgell.png" alt="미가엘관"
                    onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
                <img id="leo_13" src="static/img/13_dormitory.png" alt="행복기숙사"
                    onclick="leo_scn_hide(), leo_jg_hide(), out(leo_1), out(leo_2), out(leo_3), out(leo_11), out(leo_5), out(leo_6), out(leo_7), out(leo_12), out(leo_13), out(leo_10)">
                <p id="leo_molla"></p>
                <p id="leo_ala"></p>
            </div>
        </div>
    </div>
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
</body>

</html>